### ISSUE TITLE
Rev 2 case files

### ISSUE THREAD

**Issue by tott** [keebio/viterbi-case#3]
Will these case files work for the Rev 2 PCB and if not, are there any plans for an updated version and when can it be expected?

**Comment by carlosrfernandez** [comment]
I had a friend print the middle layer case for the rev2 and it doesn't fit the plates.

I'm not very familiar with 3D printing, but I don't think the models for revision 1 will work on Rev2.

It would be cool if they were made available...

**Comment by carlosrfernandez** [comment]
@tott it seems the repo has now been updated with the rev2 cases. I'll try printing it. 

I think this issue can now be closed.
